### ISSUE TITLE
DTYPE_STR is not set, does not appear to be inferred automatically

### ISSUE THREAD

**Issue by Xaenalt** [IBM/text-generation-inference#7]
On my system, I need to specify an environment variable DTYPE_STR, in previous versions it was set to bfloat16, but now it is unset. It's not clear what impact this has, but I think rather than hardcoding this, TGIS should probably infer it from the capabilities of the hardware it's running on

Exact error message is:

`Shard 0: RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
`

**Comment by njhill** [comment]
We're changing this to default to `float32` when running on CPU.

**Comment by njhill** [comment]
This is addressed in the latest update.
