### ISSUE TITLE
TGIS fails to load model when not in a directory

### ISSUE THREAD

**Issue by Xaenalt** [IBM/text-generation-inference#8]
One quirk we've observed, that has confused several engineers on our team is that when loading a model, TGIS looks for models by directory name underneath RUNTIME_LOCAL_MODELS_DIR, this is a bit counterintuitive when the user is only looking to serve a single model. For example in KServe deployments, it's common to store the model artifacts as something like s3://models/flan-t5-caikit with flan-t5-caikit holding the config.yml and artifacts/ directory. However, the storage-initializer will by default grab everything at a given path, so you'd end up with something that looks like
```
tree /mnt/models
models
├── artifacts
└── config.yml
```
This will cause TGIS to fail to find the model, with a rather baffling error message:
```
{"channel": "MODEL-LOADER", "exception": null, "level": "error", "log_code": "<RUN98613924E>", "message": "load failed to find model: /mnt/models/artifacts with error: FileNotFoundError('Module load path `/mnt/models/artifacts` does not contain a `config.yml` file.')", "model_id": "artifacts", "num_indent": 0, "thread_id": 140634028602368, "timestamp": "2023-07-25T10:58:40.073875"}
```

If the target directory contains a config.yml, could the logic be modified to just load the model at that location, and generate a name from the config.yml

**Comment by njhill** [comment]
@Xaenalt this is related to other layers on top of TGIS and not anything to do with TGIS itself. `RUNTIME_LOCAL_MODELS_DIR` is not an env var that TGIS is aware of. The log message you quoted doesn't come from TGIS.

Probably this is a question for the caikit repo?

**Comment by alex-jw-brooks** [comment]
Yeah, that is coming out of caikit runtime (more specifically [here](https://github.com/caikit/caikit/blob/main/caikit/runtime/model_management/model_loader.py#L123))
